### ISSUE TITLE
Use #pragma once instead of tradtional #ifndef header guard pattern

### ISSUE THREAD

**Issue by Brett208** [OutpostUniverse/HFL#12]
I'm not sure #pragma once is fully standard compliant C++, but it is a lot easier to read and maintain. Any issue switching over to using #pragma once in the headers?

**Comment by DanRStevens** [comment]
I was thinking similarly. The `#pragma once` directive is not standard, but it is widely supported. I'm pretty sure it would be supported by all compilers we are likely to care about. It may also perform better from a compile time perspective.

If you're concerned about standards conformance, you could use both techniques together, putting `#pragma once` first, though honestly I think I would prefer to just stick with a simple `#pragma once`.
