### ISSUE TITLE
Add ability to GET/SET a guard post and turret contained in a ConVec

### ISSUE THREAD

**Issue by Brett208** [OutpostUniverse/HFL#32]
Add a helper function that allow checking what turret a guard post has that is contained in a ConVec. 

Add another function that allows placing a guard post with a specific turret within a turret.

Consider placing the functions in UnitEx.

**Comment by Brett208** [comment]
I have the Get portion working on my machine. Out of time tonight to write the Set portion. Although, I suspect it will not be difficult now that I identified the proper field within OP2Unit.

Before closing this issue, the datasheet in the SVN for ollydbg should be updated as well.

**Comment by Brett208** [comment]
I tried updating the ollydbg datasheet by counting back from timerEMP to conVecCargoTurret. However, the data doesn't fit properly. I cannot seem to reconcile HFL to the text file. I wonder if there is a mistake in the text file?

**Comment by DanRStevens** [comment]
I'm not entirely clear on what you did.

I suspect the problem is that HFL amalgamates info for a bunch of different units, so really doesn't provide a proper layout for any one specific unit.
